# Permitir tr치fico desde A hacia B
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-a-to-b
spec:
  podSelector:
    matchLabels:
      app: b  # Aplica a los Pods con la etiqueta "app: b"
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: a  # Permite conexiones desde Pods con la etiqueta "app: a"
      ports:
        - protocol: TCP
          port: 80  # Limita el tr치fico al puerto 80

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: block-b-to-a
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: b
  policyTypes:
    - Egress
  egress: []  # Esta configuraci칩n bloquea todo el tr치fico de salida.